### PR TITLE
Add SSH Cloning

### PR DESCRIPTION
**Pull request by snowe2010**
Handle ssh credentials properly. 

* Make 'Git Settings' tabbed
  * Tab for HTTPS Settings
    * Username and Password 
  * Tab for SSH Settings
    * SSH Private Key Location
    * SSH Private Key Passphrase (if needed)
* If git url is an ssh url then use SSH key to clone, fetch, pull
* Allow providing ssh passphrase if the ssh key is password protected

chrome_2018-07-21_19-47-03
chrome_2018-07-21_21-28-19

### CODE REVIEW

**Comment by ErnestOrt** [comment]
Thanks @snowe2010 for time invested here!!

We will review it and we are going to tested before releasing it.

We are going to apply necessary chenges in order to keep code homogenized, it could take few days.

Cheers and do not forget to provide an star!

**Comment by snowe2010** [comment]
@ErnestOrt no problem. If you have specific code styles you'd like applied or something rearchitected let me know and I can take a stab at it as well. It seems like it could be better organized, but I wasn't sure how you'd want it done, so I did it the easiest way possible.

**Comment by snowe2010** [comment]
Hi @ErnestOrt, is there anything I need to do to help get this PR merged? And also what is the best place to have discussion about the direction of the application? Some of my team members have some suggestions that I'd wonder if you'd like to hear.

**Comment by ErnestOrt** [comment]
Hi @snowe2010 ,

I was planning to review it during this weekend.

Regarding suggestion, we would be really glad to hear, and even implementing, them. I would recommend to open an issue for each suggestion so we can comment them separately. Moreover, they will be labelled as improvement.

Thanks in advance for your time invested on Trampoline!

**Comment by snowe2010** [comment]
👏

**Pull request merged**
